name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          cache: npm

      - run: npm ci

      - run: npm run compile:test

      - run: npm run test:coverage -- --test-reporter=lcov --test-reporter-destination=.coverage-lcov.info

      # - run: apk add git curl gnupg coreutils

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          file: .coverage-lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}